name: heimdall test suit

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  anthropic:
    name: anthropic/completion and streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: run
        run: go test -v providers/anthropic_test.go
        env:
          ANTHROPIC_API_KEY: ${{secrets.ANTHROPIC_API_KEY}}
  # perplexity:
  #   name: perplexity/completion and streaming
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.26'
  #     - name: run
  #       run: go test -v providers/perplexity_test.go
  #       env:
  #         PERPLEXITY_API_KEY: ${{secrets.PERPLEXITY_API_KEY}}
  google:
    name: google/completion and streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: run
        run: go test -v providers/google_test.go
        env:
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
  openai:
    name: openai/completion and streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: run
        run: go test -v  providers/openai_test.go
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
  vertex:
    name: vertex/completion and streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: run
        run: go test -v providers/vertexai_test.go
        env:
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
  grok:
    name: grok/completion and streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: run
        run: go test -v providers/grok_test.go
        env:
          GROK_API_KEY: ${{secrets.GROK_API_KEY}}
